### ISSUE TITLE
Flopper deletes unplaceable fluids

### ISSUE THREAD

**Issue by Tfarcenim** [CyclopsMC/Flopper#13]
Upon breaking a machine that a flopper is attached to, the flopper will then void all it's contents if it happens to be an unplaceable fluid

- Flopper: 1.0.5 + silents mechanisms  0.6.9+42
- Minecraft: 1.14.4
- Forge: 28.1.90

gif of demonstration https://cdn.discordapp.com/attachments/534634673796808714/649301942690119691/2019-11-27_12-33-36.gif

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
