### ISSUE TITLE
Flopper will get disappear my bucket. (Very important)

### ISSUE THREAD

**Issue by RainEffect** [CyclopsMC/Flopper#14]
I found a bug when I using "Flopper". 
When I right-click a "Flopper" with an empty reserve of less than 1000mb using a bucket with fluid, my bucket will disappear directly and the fluid will not be injected.

- Flopper: 1.0.3
- MineCraft: 1.12.2
- Forge: 14.23.5.2847

PS: I'm sorry but my English is not very good.

**Comment by rubensworks** [comment]
What kind of fluid are you using?

Can you reproduce this problem with vanilla fluids, and without any other mods installed?

**Comment by RainEffect** [comment]
I'm using a modpack name call "EngiTech2" when I found this bug.
([github] / [curseforge])

[github]: https://github.com/dong031001/EnigTech2
[curseforge]: https://www.curseforge.com/minecraft/modpacks/enigtech-2

**Comment by rubensworks** [comment]
Please report this first to the modpack author, this could be a pack-specific thing.

**Comment by RainEffect** [comment]
Unfortunately, this modpack's author is my friend...
And I still working for this...

**Comment by RainEffect** [comment]
OK I have been found that mod: InventoryTweaks
When I open that "Auto-refill", it will clear my bucket and will not fill that "Flopper".

**Comment by RainEffect** [comment]
![Image for this BUG](https://user-images.githubusercontent.com/14258727/70904926-8da95480-203d-11ea-8c7c-630b7fcbe92b.gif)

**Comment by rubensworks** [comment]
@RainEffect I suggest you report this to InventoryTweaks, as this works fine in Vanilla.
