### ISSUE TITLE
Crash when Flopper tries to place XP fluid

### ISSUE THREAD

**Issue by aleferna12** [CyclopsMC/Flopper#17]
Description:
When the flopper tries to place XP fluid from Mob Grinding Utils (a liquid that normally can't be placed on the world) bellow itself, the game crashes. After the first crash, the game will crash after a second or two whenever you enter it, as the flopper continuously tries to place the liquid. I'm unaware if this happens with other non-placeble liquids, as I couldn't think of any other to test.

Steps to reproduce:
Have a flopper with no block beneath and click it while holding a fluid XP bucket, after a few ticks the game shall crash

[latest.log](https://github.com/CyclopsMC/Flopper/files/4530098/latest.log)

**Comment by rubensworks** [comment]
Please fill in the proper issue template.
