### ISSUE TITLE
Giving flopper color or model visually distinctive from that of hopper

### ISSUE THREAD

**Issue by AbacusOperator** [CyclopsMC/Flopper#19]
#### Issue type:

Confusion in large constructions, that just requires inconvenient clicking.

____

#### Short description:

Flopper being visually distinctive from hopper. Perhaps the same lighter texture that icon uses.

**Comment by rubensworks** [comment]
I'm not sure what you mean, can you clarify?

**Comment by AbacusOperator** [comment]
If I want to build some large machine that uses both floppers and hoppers, it can be confusing to distinguish sometimes where did I put hopper and where I did I put flopper. So I have to check which is which by clicking (checking by hand). Can you make them different by color, so just by looking at flopper from afar you can't confuse it with hopper.
