### ISSUE TITLE
Waterlogging the block above the flopper

### ISSUE THREAD

**Issue by DaedalusGame** [CyclopsMC/Flopper#20]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

Currently, floppers can pull fine from normal fluid blocks but cannot pull from waterlogged blocks
![java_qjJilDZG5i](https://user-images.githubusercontent.com/9559216/122395820-a880c000-cf77-11eb-8f5d-d03649c96c07.png)
The design on the left works fine, but the design on the right does not pull any fluid.
Is there any chance we could get support for the design on the right aswell?

**Comment by rubensworks** [comment]
Thanks for the suggestion!
