### ISSUE TITLE
Flopper glitching water texture 

### ISSUE THREAD

**Issue by Archuhi3** [CyclopsMC/Flopper#21]
#### Issue type: Glitching the sea water texture

- :bug: Bug 

____

#### Steps to reproduce the problem:

1.  Placing a flopper in the sea anywhere.

#### Expected behaviour: To not glitch the whole sea texture. 

____

#### Versions: CyclopsCore-1.16.5-1.11.7

- This mod: Seaopolis 6.1
- Minecraft: 1.16.5
- Forge: 36.2.2

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Can't reproduce the problem. Please try again without any other mods installed.
