### ISSUE TITLE
Crash on loading with hopper +

### ISSUE THREAD

**Issue by benbenlaw** [CyclopsMC/Flopper#22]
#### Issue type:

Game crashes on start up with https://www.curseforge.com/minecraft/mc-mods/hopper
And yes im using the forge version haha

____

#### Short description:

Crash on agme start up

#### Steps to reproduce the problem:

install
https://www.curseforge.com/minecraft/mc-mods/hopper
and
flopper
game crash on start up

#### Expected behaviour:

____

#### Versions:

- This mod: 1.0.7
- Minecraft: 1.16.5
- Forge: 36.2.2

#### Log file:

[crash-2021-09-07_16.31.45-client.txt](https://github.com/CyclopsMC/Flopper/files/7122670/crash-2021-09-07_16.31.45-client.txt)

[debug.log](https://github.com/CyclopsMC/Flopper/files/7122666/debug.log)
[latest.log](https://github.com/CyclopsMC/Flopper/files/7122667/latest.log)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by benbenlaw** [comment]
no problem :)
