### ISSUE TITLE
Disappearing buckets

### ISSUE THREAD

**Issue by benbenlaw** [CyclopsMC/Flopper#23]
#### Issue type:

- :bug: Bug 

____

#### Short description:

if a flopper has less space than a buckets worth of fluid right clicking removes the bucket

#### Steps to reproduce the problem:

have a flopper with say 4400 mb of a fluid then try add a buckets worth of fluid to it, bucket disapears 

1. ...

#### Expected behaviour:

bucket doesnt get consumed 

____

#### Versions:

- This mod: 1.1.0
- Minecraft: 1.16.5
- Forge: 36.2.4

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by benbenlaw** [comment]
no problem :)
