### ISSUE TITLE
Duplication bucket

### ISSUE THREAD

**Issue by MickeyMouseYT** [CyclopsMC/Flopper#27]
Issue type:
* 🐛 Bug

------------------------------------------------------------------

Short description:

Hi just my friend just found a duplication bug ( bucket ) I will show you by video

https://youtu.be/eoWyuGWWaak

**Comment by rubensworks** [comment]
Please fill in all required information of the bug report template, such as mod versions, etc...

**Comment by MickeyMouseYT** [comment]
Do you look video ?

Minecraft : 1.16.5
Forge : 36.2.26

Version : 
Flopper-1.16.5-1.1.1.jar

Information of bug :
When you put your hand left a bucket and sneak + click right a flopper you will have duplication bucket iron in hand left and other is fulled with a bucket ( water, biomass, ... )

**Comment by MickeyMouseYT** [comment]
Minecraft : 1.16.5
Forge : 36.2.26
