### ISSUE TITLE
Crash in newer versions of forge with Fluid.getAttributes()

### ISSUE THREAD

**Issue by zach2039** [CyclopsMC/Flopper#28]
#### Issue type:

- :bug: Bug

____

#### Short description:

Newer versions of Forge don't have a Fluid.getAttributes() method, causing a crash.

#### Steps to reproduce the problem:

1. Try to place a flopper down and fill it with a fluid
2. Crash

#### Expected behaviour:

Place flopper and use without crash.

____

#### Versions:

- This mod: 1.19-1.1.2
- Minecraft: 1.19
- Forge: 41.0.45

#### Log file:

[https://pastebin.com/Pf4parGR](https://pastebin.com/Pf4parGR)

**Comment by rubensworks** [comment]
Thanks for reporting!
