### ISSUE TITLE
Bowl water blacklist flopper possibility ?

### ISSUE THREAD

**Issue by MickeyMouseYT** [CyclopsMC/Flopper#30]
#### Issue type:

- Duplication water with bowl mod (botania/ftb dripper)

____

#### Question:

- I wanted to ask if it is possible to blacklist the bowl because the bowl does not consume water (not as a bucket) so the bowl has the possibility of putting to flopper to re-have water like "infinity water" that which I did not want not.

**Comment by rubensworks** [comment]
Sounds like a bug in this bowl mud, best to report it there.

**Comment by MickeyMouseYT** [comment]
> Sounds like a bug in this bowl mud, best to report it there.

I don't understand ? What you mean ?

**Comment by MickeyMouseYT** [comment]
I have to report for bug ?
