### ISSUE TITLE
Server crash with Flopper / CyclopsCore

### ISSUE THREAD

**Issue by Micaxs** [CyclopsMC/Flopper#31]
#### Issue type:

- :bug: Bug
- 
____

#### Short description:

A flopper is causing the server to crash.

#### Steps to reproduce the problem:

- Flopper underneath an IntegratedDynamics squeezer (manual one) into a basic portalable tank from Portable Tanks mod.

#### Expected behaviour:

- Not crash server would be nice? :D
____

#### Versions:

- This mod: 1.1.4
- Minecraft: 1.20.1
- Forge: 1.20.1-47.2.16

#### Log file:

https://mclo.gs/AbqsT7a

**Comment by rubensworks** [comment]
Thanks for reporting!
