### ISSUE TITLE
[World Local] Persistent Fatal Crash

### ISSUE THREAD

**Issue by AndreLouisIssa** [CyclopsMC/Flopper#5]
#### Issue type: 

- :warning: Persistent Fatal Crash

____

#### Short description: 
Something to do with fluiducts and floppers
Flopper tileentity crashes the game when world load or first instance of the bug
 (until mod is removed and forge clears the tiles from said world)

#### Steps to reproduce the problem:

1. Flopper into fluiducts
1. When fluid is flowing break fluiducts
1. Crash?
        
I uninstalled the mod to fix it so I can't test if this is reproducible consistently, wouldn't want to risk doing further damage to my world anyway
#### Expected behaviour:

Game shouldn't have crashed
My world should not have become permanently unusable unless the mod was removed :P 
____

#### Versions:

- This mod: Flopper-1.12.2-1.0.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2814

#### Log file:

https://paste.dimdev.org/xubuzazuya.mccrash

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by rubensworks** [comment]
@MagicGonads It looks some mod may be (incorrectly) modifying the way how in-world fluids are handled, because this crash is impossible in vanilla (world is null, while methods are being called on that world before).

Could you try reproducing your issue without any other mods installed?

**Comment by AndreLouisIssa** [comment]
Not willing to do that at the moment, sorry.
I won't be reinstalling this mod until I start a new world anyway (which will entail a different mod setup most likely)

**Comment by rubensworks** [comment]
Ok, assuming this is a mod in your pack then.
