### ISSUE TITLE
Feature Request: 'Inspirations' style flopper pipes

### ISSUE THREAD

**Issue by AndreLouisIssa** [CyclopsMC/Flopper#6]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Pipes similar to those from the Inspirations mod that flow in a single direction like mini-floppers which don't auto extract but do auto export. Can move upwards based on config.
Are oriented (into) based on the blockface placed upon

**Comment by rubensworks** [comment]
This seems out-of-scope for this mod. The only goal of this mod is to add a single, simple Flopper :-)

**Comment by AndreLouisIssa** [comment]
Then perhaps a branch/addon would be appropriate

Only asking because I like how simple the inspirations pipes are, they work exactly like normal hoppers except without the cycles for checking items to gather from the world
