### ISSUE TITLE
[1.14.4] Server Crash Flopper on Lava Generator

### ISSUE THREAD

**Issue by Lice2** [CyclopsMC/Flopper#8]
#### Issue type:

- :bug: Bug

____

#### Steps to reproduce the problem:

1. The server crashes when you put the flopper on a lava generator from Silent Mechanism.

#### Expected behaviour:

____

#### Versions:

- This mod: Flopper-1.14.4-1.0.4.jar
- Minecraft: 1.14.4
- Forge: 1.14.4-forge-28.1.36

#### Log file:

[https://pastebin.com/zePhAqqc](url)
[https://pastebin.com/vGkJRrwJ](url)
[https://pastebin.com/JQERC1Yz](url)

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
